# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bc00ba5f9b798aecfc16c6158abb9546aa2b521ef9b6c4bdf2c1d775d871b479a262a7cf90410d96aff0eda7e16fefa79b4c12c68b07819b0578e4996b73541

test:
  secret_key_base: df9dfc1c4d032820bc86bbe6ab668e8c4b231cefed4fc07fce0d03620417536847c033330ecb8cd010c9ae20bb3b6da9160e6303da53a4b788a22e406299c446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
